#+title: category theory
#+html_link_home: index
#+OPTIONS: tex:t
#+html_mathjax: align: left indent: 5em tagside: left
#+latex_header: \usepackage{tikz}
#+latex_header: \usepackage{tikz-cd}

** small category

	 small category is a category such that all of its objects form a set and all of its morphisms form a set.

** product category

	 For any two categories ğ’œ, â„¬, we can build a product of them as a category, write as ğ’œÃ—â„¬

	 ğ’ªğ’·(ğ’œÃ—â„¬) = ğ’ªğ’·(ğ’œ) Ã— ğ’ªğ’·(â„¬)
	 (ğ’œÃ—â„¬)((A, B), (A', B')) = ğ’œ(A, A') Ã— â„¬(B, B')

	 As well, we define âˆ˜ as

	 (f, g) âˆ˜ (h, j) = (fâˆ˜h, gâˆ˜j)

	 and define identity of (A, B) as

	 1(A, B) = (1A, 1B)

* definition: monic/monomorphism

A morphism $f : A \to B$ is monic if for any $s, t : M \to A$, $f \circ s = f \circ t$ implies $s = t$.

+ monic is the generalization of injective
+ æ›´æ³›åŒ–çš„é †åºæ˜¯ isomorphism ~> split monic ~> monic

** proposition: isomorphism implies monic

Let $f : A \to B$ be an isomorphism, then there has $f^{-1}$ (refers to [[isomorphism]])

\begin{equation}
f s = f t \\
\implies f^{-1} f s = f^{-1} f t \\
\implies s = t
\end{equation}

Such conditions statisfy the definition of monic.

** definition: split monic

A monic $f : A \to B$ is split if there has a $g : B \to A$ makes $g f = id_A$, and hence $f s = f t \implies g f s = g f t \implies s = t$.

* definition: epic/epimorphism

	A morphism $f : A \to B$ is an epic, if for any $s, t : B \to M$, $s f = t f$ implies $s = t$.

+ epic is the generalization of surjective
+ æ›´æ³›åŒ–çš„é †åºæ˜¯ isomorphism ~> split epic ~> epic

** proposition: isomorphism implies epic

It has a similar proof as monic.

** definition: split epic

A monic $f : A \to B$ is split if there has a $g : B \to A$ makes $f g = id_B$, and hence $s f = t f \implies s f g = t f g \implies s = t$.

** isomorphism

ä»¤ $f : A \to B$ æ˜¯ä¸€å€‹ morphism ä¹‹å¾Œæœ‰ $g$ ä»¤ $g f = id_A$ åŒæ™‚ $f g = id_B$ï¼Œ$g$ äº¦å¯è¨˜ç‚º $f^{-1}$

å¦å¤–åœ¨ *Set* åº•ä¸‹

+ monic = injective
+ epic = surjective
+ isomorphism = bijective = injective + surjective

* tranditional abstract algebra

** group by category

	 The group axioms can be formed by category thinking, that's a small-category that
	 
	 1. only has one object
	 2. all morphisms are isomorphisms

	 In this situtation, we have the following mapping

  | category â„­     | corrresponding group G |
  |----------------+------------------------|
  | morphisms in â„­ | elements of G          |
  | â—‹ in â„­         | â‹… in G                 |
  | 1â„­             | e âˆˆ G                  |

	 A more advanced idea is, viewing group as a list of operations (partially applied ~â‹… a~), with e as initial state

	 Then the category diagram will just reflect the idea

* Functor

	A functor ~F : ğ’œ â†’ â„¬~ consists

	1. function makes ğ’ªğ’·(ğ’œ) to ğ’ªğ’·(â„¬), write as A âŸ¶  F(A)
	2. for every morphism ~f : A â†’ A'~ in ğ’œ, makes corrresponding morphism in â„¬, write as f âŸ¶  F(f)
	3. composition of morphism are preserved
	4. identities are preserved

** Free functor (informal term)

	Given any set ~S~, one can build the *free group* ~F(S)~ on ~S~. For example, said ~S = {x, y, z}~, insert ~e~, ~xâ»Â¹~, ~yâ»Â¹~, ~zâ»Â¹~ makes a group (informally). Just like we have in mind, ~x â‹… xâ»Â¹ = e~, and so on. This group is the *free group* of ~{x, y, z}~. On the other hand, this ~F~ became a functor, from *Set* to *Grp*. Maps of sets ~S~, ~S'~, rise to a homomorphism of groups.

	The same can be done for *Set* to *Vectâ‚–*, *Set* to *CRing*, and many. Such thing is what we called free functor, informally.

** Definition: presheaf

	 A presheaf on category ğ”„ is a functor ğ”„áµ’áµ– â†’ *Set*

** TODO Definition: faithful

* TODO definition: slice category

	A slice category is about an object ~a~ and its category ~ğ˜¼~.

	This category would be write as ~ğ˜¼/a~, which
	1. objects are pair ~(b, f : b â†’ a)~
	2. morphisms are those morphisms of ~ğ˜¼~ makes whatever ~g : b â†’ b'~ makes ~f = f' g~, where ~f' : b' â†’ a~

\begin{equation}
	\[\begin{tikzcd}
		b &&&& {b'} \\
		\\
		&& a
		\arrow["f", from=1-1, to=3-3]
		\arrow["{f'}"', from=1-5, to=3-3]
		\arrow["g"', from=1-1, to=1-5]
	\end{tikzcd}\]
\end{equation}
