* category theory

** small category

	 small category is a category such that all of its objects form a set and all of its morphisms form a set.

** product category

	 For any two categories ğ’œ, â„¬, we can build a product of them as a category, write as ğ’œÃ—â„¬

	 ğ’ªğ’·(ğ’œÃ—â„¬) = ğ’ªğ’·(ğ’œ) Ã— ğ’ªğ’·(â„¬)
	 (ğ’œÃ—â„¬)((A, B), (A', B')) = ğ’œ(A, A') Ã— â„¬(B, B')

	 As well, we define âˆ˜ as

	 (f, g) âˆ˜ (h, j) = (fâˆ˜h, gâˆ˜j)

	 and define identity of (A, B) as

	 1(A, B) = (1A, 1B)
	
* tranditional abstract algebra

** group by category

	 The group axioms can be formed by category thinking, that's a small-category that
	 
	 1. only has one object
	 2. all morphisms are isomorphisms

	 In this situtation, we have the following mapping

  | category â„­     | corrresponding group G |
  |----------------+------------------------|
  | morphisms in â„­ | elements of G          |
  | â—‹ in â„­         | â‹… in G                 |
  | 1â„­             | e âˆˆ G                  |

	 A more advanced idea is, viewing group as a list of operations (partially applied ~â‹… a~), with e as initial state

	 Then the category diagram will just reflect the idea

* Functor

	A functor ~F : ğ’œ â†’ â„¬~ consists

	1. function makes ğ’ªğ’·(ğ’œ) to ğ’ªğ’·(â„¬), write as A âŸ¶  F(A)
	2. for every morphism ~f : A â†’ A'~ in ğ’œ, makes corrresponding morphism in â„¬, write as f âŸ¶  F(f)
	3. composition of morphism are preserved
	4. identities are preserved

** Free functor (informal term)

	Given any set ~S~, one can build the *free group* ~F(S)~ on ~S~. For example, said ~S = {x, y, z}~, insert ~e~, ~xâ»Â¹~, ~yâ»Â¹~, ~zâ»Â¹~ makes a group (informally). Just like we have in mind, ~x â‹… xâ»Â¹ = e~, and so on. This group is the *free group* of ~{x, y, z}~. On the other hand, this ~F~ became a functor, from *Set* to *Grp*. Maps of sets ~S~, ~S'~, rise to a homomorphism of groups.

	The same can be done for *Set* to *Vectâ‚–*, *Set* to *CRing*, and many. Such thing is what we called free functor, informally.

** Definition: presheaf

	 A presheaf on category ğ”„ is a functor ğ”„áµ’áµ– â†’ *Set*

** TODO Definition: faithful
