name: Publish
on: [push]

jobs:
  export:
    runs-on: ubuntu-latest
    - name: Checkout
      uses: actions/checkout@v2
    - name: Export org files
      uses: tecosaur/org-knit-action@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
