name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "publish org files"
      uses: tecosaur/org-knit-action@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        force_orphan: true
